name: to_do_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  push: ^3.3.3
  go_router: ^14.8.1
  image_picker: ^1.1.2
  animations: ^2.0.11
  flutter_bloc: ^9.1.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_time_picker_spinner: ^2.0.0
  intl: ^0.20.2

  firebase_messaging: ^15.2.5
  timezone: ^0.10.0
  permission_handler: ^11.4.0
  awesome_notifications: ^0.10.1
  awesome_notifications_core: ^0.10.1
  awesome_notifications_fcm: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\icons\finance\ic_bank_card_bitcoin.png
    - assets\icons\finance\ic_bitcoin.png
    - assets\icons\finance\ic_broker.png
    - assets\icons\finance\ic_card_payment.png
    - assets\icons\finance\ic_money_box.png
    - assets\icons\finance\ic_pay_date.png
    - assets\icons\finance\ic_safe.png
    - assets\icons\finance\ic_stack_money.png

    - assets\icons\food\ic_chiken.png
    - assets\icons\food\ic_cocktail.png
    - assets\icons\food\ic_jun.png
    - assets\icons\food\ic_milk.png
    - assets\icons\food\ic_soft_drinks.png
    - assets\icons\food\ic_sweets.png
    - assets\icons\food\ic_takeout.png
    - assets\icons\food\ic_wine_cheese.png

    - assets\icons\payment\ic_basket_shop.png
    - assets\icons\payment\ic_buy.png
    - assets\icons\payment\ic_hanger.png
    - assets\icons\payment\ic_shoes.png
    - assets\icons\payment\ic_shopping_cart.png
    - assets\icons\payment\ic_washing_machine.png
    - assets\icons\payment\ic_woman_clothes.png
    - assets\icons\payment\ic_wristwatch.png
    - assets\icons\ic_question.png
    
    - assets\icons\ic_user.png
    - assets\icons\ic_arrow_down.png
    
    - assets/fonts/Blushes/Blushes_Regular.otf

  fonts:
    - family: Blushes
      fonts:
        - asset: assets/fonts/Blushes/Blushes_Regular.otf
