// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbL8nVH8Vzj6rmcb2VRmuNt54bj-EPQZ0',
    appId: '1:116232048988:web:149be01932eaee2d76f199',
    messagingSenderId: '116232048988',
    projectId: 'to-do-list-d2171',
    authDomain: 'to-do-list-d2171.firebaseapp.com',
    storageBucket: 'to-do-list-d2171.firebasestorage.app',
    measurementId: 'G-7QEJ74CQVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiEZ7LR0P1D7IxbtFvCiaUIGrCkusR9E0',
    appId: '1:116232048988:android:60db2be2ee5394cb76f199',
    messagingSenderId: '116232048988',
    projectId: 'to-do-list-d2171',
    storageBucket: 'to-do-list-d2171.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdkBanmqmVUVz8yyHYoNrAQv75itTlcSg',
    appId: '1:116232048988:ios:39dcdad506290c6e76f199',
    messagingSenderId: '116232048988',
    projectId: 'to-do-list-d2171',
    storageBucket: 'to-do-list-d2171.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdkBanmqmVUVz8yyHYoNrAQv75itTlcSg',
    appId: '1:116232048988:ios:39dcdad506290c6e76f199',
    messagingSenderId: '116232048988',
    projectId: 'to-do-list-d2171',
    storageBucket: 'to-do-list-d2171.firebasestorage.app',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbL8nVH8Vzj6rmcb2VRmuNt54bj-EPQZ0',
    appId: '1:116232048988:web:f06cd76cc2fb8bc376f199',
    messagingSenderId: '116232048988',
    projectId: 'to-do-list-d2171',
    authDomain: 'to-do-list-d2171.firebaseapp.com',
    storageBucket: 'to-do-list-d2171.firebasestorage.app',
    measurementId: 'G-VXQSQYXEYS',
  );
}
